"""
Dataset card: a committed, human-readable snapshot of what the model will be
trained on. Regenerated by `python cli.py report`; lives in ml/reports/.
"""
from __future__ import annotations

import json
import logging
import math
from collections import Counter, defaultdict
from datetime import date
from pathlib import Path

from config.settings import settings
from dataprep.ingest import load_manifest
from dataprep.split import load_split

logger = logging.getLogger("ml.report")

SIZE_BUCKETS = [(0, 16), (16, 32), (32, 64), (64, 128), (128, 10_000)]


def _box_side(b: list[float]) -> float:
    return math.sqrt(max((b[2] - b[0]) * (b[3] - b[1]), 0.0))


def build_card() -> str:
    manifest = load_manifest()
    split = load_split()
    entries = manifest["entries"]
    usable = [
        e for e in entries
        if e["quarantine_reason"] is None and e["label_state"] != "unannotated"
    ]
    bucket_of = {c: a["bucket"] for c, a in split["assignment"].items()}

    lines = [
        "# Dataset card — NAL defect detection",
        "",
        f"_Generated {date.today().isoformat()} · snapshot `{manifest['snapshot_id']}` · "
        f"split `{split['split_id']}` (seed {split['seed']}, K={split['k_folds']})_",
        "",
        "Single class: **Nicht ausreichend Lot** (insufficient solder). "
        "Brücke/Fahne boxes are dropped to background by design (kept in "
        "Label Studio; recorded as `other_boxes` for eval FP tagging).",
        "",
        "## Photos",
        "",
        "| state | count |",
        "|---|---|",
    ]
    states = Counter(e["label_state"] for e in entries)
    for s, n in sorted(states.items()):
        lines.append(f"| {s} | {n} |")
    quarantined = [e for e in entries if e["quarantine_reason"]]
    lines += [
        f"| quarantined (excluded, any state) | {len(quarantined)} |",
        f"| **usable for train/eval** | **{len(usable)}** |",
        "",
        "## Per capture session (usable photos)",
        "",
        "| session | photos | positives | NAL boxes | buckets |",
        "|---|---|---|---|---|",
    ]
    by_session: dict[str, list[dict]] = defaultdict(list)
    for e in usable:
        by_session[e["session"]].append(e)
    for session in sorted(by_session):
        es = by_session[session]
        buckets = Counter(bucket_of[e["capture_id"]] for e in es)
        lines.append(
            f"| {session} | {len(es)} | "
            f"{sum(1 for e in es if e['label_state'] == 'annotated_positive')} | "
            f"{sum(len(e['nal_boxes']) for e in es)} | "
            f"{', '.join(f'{b}:{n}' for b, n in sorted(buckets.items()))} |"
        )

    lines += ["", "## Split composition (usable photos)", "",
              "| bucket | photos | positives | NAL boxes |", "|---|---|---|---|"]
    per_bucket: dict[str, list[dict]] = defaultdict(list)
    for e in usable:
        per_bucket[bucket_of[e["capture_id"]]].append(e)
    for bucket in sorted(per_bucket):
        es = per_bucket[bucket]
        lines.append(
            f"| {bucket} | {len(es)} | "
            f"{sum(1 for e in es if e['label_state'] == 'annotated_positive')} | "
            f"{sum(len(e['nal_boxes']) for e in es)} |"
        )

    sides = sorted(
        _box_side(b) for e in usable for b in e["nal_boxes"]
    )
    lines += ["", "## NAL box sizes (sqrt-area px at native 2616×1960)", "",
              "| bucket | boxes |", "|---|---|"]
    for lo, hi in SIZE_BUCKETS:
        n = sum(1 for s in sides if lo <= s < hi)
        label = f"{lo}–{hi}" if hi < 10_000 else f">{lo}"
        lines.append(f"| {label} px | {n} |")
    if sides:
        mid = sides[len(sides) // 2]
        lines += [
            "",
            f"min {sides[0]:.0f} · median {mid:.0f} · max {sides[-1]:.0f} px "
            f"({len(sides)} boxes). Boxes >300 px: "
            f"{sum(1 for s in sides if s > 300)} (tile-fragmentation caveat "
            "→ IoS merge at stitch time).",
        ]

    tiles_prov = settings.tiles_dir / "ds_v1" / "provenance.json"
    if tiles_prov.exists():
        p = json.loads(tiles_prov.read_text(encoding="utf-8"))
        lines += [
            "",
            "## Tiles",
            "",
            f"- tiler `{p['tiler_version']}`: {p['tile_size']} px / stride {p['stride']}, "
            f"encoding `{p['encoding']}`",
            f"- {p['n_tiles']} tiles from {p['n_photos_tiled']} photos; "
            f"{p['n_positive_tiles']} positive tiles, {p['n_tile_boxes']} tile boxes",
            f"- train oversample K = {p['oversample_k']} "
            f"(target positive fraction {p['oversample_target']})",
            f"- dataset_fingerprint `{p['dataset_fingerprint'][:16]}…`",
        ]

    review = [e for e in entries if e["review_note"]]
    if review:
        lines += ["", "## Review list", ""]
        for e in review:
            lines.append(f"- `{e['capture_id']}`: {e['review_note']}")

    return "\n".join(lines) + "\n"


def run() -> Path:
    settings.reports_dir.mkdir(parents=True, exist_ok=True)
    out = settings.reports_dir / "dataset_card.md"
    out.write_text(build_card(), encoding="utf-8")
    logger.info(f"dataset card written: {out}")
    return out
